name: Actions Workflow

on:
  push:
    branches: # we can use this to filter the branches we want perform this workflow when we push (like deployment for example we want to deploy only when we push to master)
      - master
      - 'feature/*' # matches feature/featureA , feature/featureB doesn't match feature/feature/a
      - 'feature/**' #matches matches feature/featureA , feature/featureB and feature/feature/a
      - '!feature/featC' #ignore this spcific branch when push to
    tags:
      - v1.* # when pushing to specific version
    paths:
      - '**.js' # when changing any js file
  #schedule: # running the workflow on specific time
   # - cron: "* * * * *" #any value min hour day(month) month day(week)
  pull_request:
    types:
      - closed
      - assigned
      - opened
      - reopened
      - review_requested

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # action / the checkout action is very useful for getting the project files and allows us to run test or build for those files
        uses: actions/checkout@v3 # run git fetch and git checkout
      - name: List Files After Checkout #shell command
        run: |
          pwd
          ls -a
      - name: Simple Js Action #action
        id: greet
        uses: actions/hello-world-javascript-action@e76147da8e5c81eaf017dede5645551d4b94427b # it is better not to use branch name so even version or commit id for major break throughs
        with: 
          who-to-greet: Lilyan
      - name: Log Greeting time  #shell command
        run: echo "${{ steps.greet.outputs.time }}"
