name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: #if we add the container so any step we will execute it will run over this container not inside the VM directly
      image: node:18-alpine3.15
    steps:
      - name: Log node version
        run: |
          node -v 
          cat /etc/os-release