name: Matrix

on: push

jobs:
  node-version:
    strategy: #running jobs in different parameters each time
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest] #run over different VM so 3x3 the job will run 9 times
        node_version: [6,8,10] 
      fail-fast: true #all the test cases are dependent on each other so if one of them fails it will stop the others
      max-parallel: 2 # limit the number of parrellel job that run at the same time
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node node version 
        run: node -v
      - uses: actions/setup-node@v3 #changing the node version on VM
        with:
          node-version: ${{ matrix.node_version}} # like mapping the 3 values
      - name: Log new node version
        run: node -v

        