name: Shell Command

on: [pull_request]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    timeout-minutes:  360 #this is default we can change to something more or less (can be used on steps or jobs)
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]  # this key is used when we run this job after a specific jobs are done
    steps:
      - name: Directory PowerShell
        run: Get-Location
      - name: Directory Bash
        run: pwd
        shell: bash
